### PR TITLE
Fix Windows deployment paths

### LINKED ISSUE #836: Unable to import module 'src\\email-password\\signup-lambda' on Windows
```
"logs": [
    {
      "START RequestId: a95a2f2f-": "b1c6-11e7-af17-e1bfe467d931 Version: $LATEST\nUnable to import module 'src\\email-password\\signup-lambda': Error\n    at Function.Module._resolveFilename (module.js:469:15)\n    at Function.Module._load (module.js:417:25)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\nEND RequestId: a95a2f2f-b1c6-11e7-af17-e1bfe467d931\nREPORT RequestId: a95a2f2f-b1c6-11e7-af17-e1bfe467d931\tDuration: 51.09 ms\tBilled Duration: 100 ms \tMemory Size: 512 MB\tMax Memory Used: 19 MB\t\n"
    }
  ],
  "returnValue": {
    "errorMessage": "Cannot find module '/var/task/src\\email-password\\signup-lambda'",
    "errorType": "Error",
    "stackTrace": [
      "Function.Module._load (module.js:417:25)",
      "Module.require (module.js:497:17)",
      "require (internal/module.js:20:19)"
    ]
  }
```

### LINKED ISSUE #885: Deploy not working on Windows
**Current behavior**
When requested the 'hello(name)' function returns null

**Reproduction**

Request:
`query {
  hello(name:"TEST") {
    message
  }
}`
Result:
`{
  "data": {
    "hello": null
  }
}
`

**Expected behavior?**

Should result in:
`{
  "data": {
    "hello": {message: "Hello TEST"}
  }
}`

### LINKED ISSUE #1031: Function invocation broken on Windows
**Current behavior**

I am using the `email-password` template but I get all the time `null` as response. The error message is `{"error":"Function returned invalid status code: 0. Raw body: empty.last"}`.

I am using `graphcool/0.8.0 (windows-x64) node-v8.6.0`.

**Expected behavior?**

It should create a user and return the token.

### PR DESCRIPTION
**Pull request by kbrandwijk**
This patch fixes the deployment to shared clusters from Windows. :tada:
Fixes #1031, fixes #836, fixes #885.

### CODE REVIEW

**Comment by Toosick** [comment]
💯 💯 💯 

Yeah I knew this was something wrong in the Bundler. Just didn't get down to looking into the code. Was working around the problem for now.

**Comment by kbrandwijk** [comment]
I had only Windows before, so I had nothing to compare it to. Now, with Linux Subsystem on Windows, I could finally compare the debug output for both, and that made it obvious.

**Comment by Toosick** [comment]
@kbrandwijk Is this what you installed? https://msdn.microsoft.com/en-us/commandline/wsl/install-win10

**Comment by kbrandwijk** [comment]
@Toosick yes. Works great. Can just switch within my console. Ridiculously easy:
image

**Comment by Toosick** [comment]
@kbrandwijk What is this terminal/shell you are using?

**Comment by kbrandwijk** [comment]
@Toosick cmder on Windows, using bash with powerline on Linux.

**Comment by timsuchanek** [comment]
Thanks @kbrandwijk for researching and fixing this! I tested it, works on Mac, so we're good to go :)

**Comment by kbrandwijk** [comment]
Will there be a patch release?

**Pull request merged**
