### PR TITLE
Fix Spelling

### PR DESCRIPTION
**Pull request by rcy**

### CODE REVIEW

**Comment by marktani** [comment]
Hey @rcy, please rebase and sign this GCA so I can merge your PR: https://cla-assistant.io/graphcool/framework?pullRequest=996 🙂

**Comment by rcy** [comment]
@marktani I signed the GCA and merged master into this PR branch.

**Comment by kbrandwijk** [comment]
It seems like there are no more changes to merge. Apparently all changes were already updated in the meantime...

**Comment by rcy** [comment]
yep, seems so, thats great!

**Pull request closed without merging**
